feat: basic javafx compilation support

diff --git a/jargo b/jargo
--- a/jargo
+++ b/jargo
@@ -29,6 +29,9 @@ package=""
 # Name of driver file
 driver=""
 
+# Name of primary module file
+MODULE="module-info.java"
+
 # ANSI text colors
 RESET="\e[0m"
 YELLOW="\e[1;33m"
@@ -162,7 +165,7 @@ package:$package
 driver:$driver" > $name/$CONFIG
 
     # Get current system time
-    time=$(date +"%Y-%m-%d %T")
+    local time=$(date +"%Y-%m-%d %T")
 
     # Set up Main class
     echo "package $package;
@@ -183,6 +186,11 @@ public class $driver {
         System.out.println(\"Hello, world!\");
     }
 }" > $name/src/$package/$driver.java
+
+    # Create module file
+    echo "module $name {
+    
+}" > $name/src/$MODULE
 
     # Set up README.md
     echo "# $name " > $name/README.md
@@ -212,7 +220,7 @@ public class $driver {
 #   1 if compilation was successful, else 0
 ################################################################################
 build() {
-    retval=0
+    local retval=0
 
     # Ensure command was run from project root
     if [ $(in_root) -ne 1 ]; then
@@ -223,20 +231,39 @@ build() {
 
     # Only recompile if needed
     if [ $(needs_rebuild) -eq 1 ]; then
-        find src/ -name "*.java" -print | xargs javac -d bin/
 
+        # Local variables for args and shifting
+        local shift_amt=-1
+        local args=()
+
+        echo INITIAL ${@}
+
+        while [ $shift_amt -ne 0 ]; do
+            # Fetch modified args from the parser
+            args+=($(arg_parser ${@}))
+
+            # Shift the args
+            shift_amt=$?
+            shift $shift_amt
+        done
+
+        #args=$(arg_parser ${@})
+        echo LEFTOVER ${@}
+
+        # Compile with new args
+        find src/ -name "*.java" -print | xargs javac ${args[@]} -d bin/
 
         # Display compilation message if no errors occurred
         if [ $? -eq 0 ]; then
 
             # Display appropriate compilation message
-            if [ ${#@} -gt 0 ]; then
-                echo -e "\t${YELLOW}COMPILED${RESET} $name with args: ${@}"
+            if [ ${#args[@]} -gt 0 ]; then
+                echo -e "\t${YELLOW}COMPILED${RESET} $name with args: ${args[@]}"
             else
                 echo -e "\t${YELLOW}COMPILED${RESET} $name"
             fi
 
-            # Compilation sucess
+            # Compilation success
             retval=1
         fi
     else
@@ -245,6 +272,33 @@ build() {
     fi
 
     return $retval
+}
+
+arg_parser () {
+
+    # Hold new argument list and shift amount
+    local args=()
+    local num=0
+
+    case "$1" in
+        "--jfx" | "--fx") # Add JFX support
+            # Consume the argument and increase the counter
+            shift 
+            num=$((num + 1))
+            args+=("--module-path $PATH_TO_FX --add-modules javafx.controls")
+            ;;
+
+        *) # No parsing needed, just check that it's not empty
+            if [ ! -z "$1" ]; then
+                args+=("$1")
+                num=$((num + 1))
+            fi
+            ;;
+    esac
+
+    echo "${args[@]}"
+
+    return $num
 }
 
 ################################################################################
@@ -269,24 +323,37 @@ run() {
     fi
 
     # By default, status is OK to run
-    status=1
+    local status=1
 
     # If the project needs to be recompiled, do so.
     if [ $(needs_rebuild) -eq 1 ]; then
-        build
+        build ${@}
         status=$?
     fi
 
+    # Local variables for args and shifting
+    local shift_amt=-1
+    local args=()
+
+    while [ $shift_amt -ne 0 ]; do
+        # Fetch modified args from the parser
+        args+=($(arg_parser ${@}))
+
+        # Shift the args
+        shift_amt=$?
+        shift $shift_amt
+    done
+
     # Only execute if compilation was successful
     if [ $status -eq 1 ]; then
-        if [ ${#@} -gt 0 ]; then
-            echo -e "\t${YELLOW}EXECUTING${RESET} $name with args: ${@}"
+        if [ ${#args[@]} -gt 0 ]; then
+            echo -e "\t${YELLOW}EXECUTING${RESET} $name with args: ${args[@]}"
         else
             echo -e "\t${YELLOW}EXECUTING${RESET} $name"
         fi
 
         # Execute driver with supplied args
-        java -cp bin/ $package.$driver ${@}
+        java -cp bin/ $package.$driver ${args[@]}
     fi
 }
 
@@ -329,6 +396,35 @@ doc() {
 
 
     echo -e "\t${YELLOW}GENERATED${RESET} docs for project under \`$name/docs/\`"
+}
+
+################################################################################
+# Adds dependencies to the project
+#
+# Arguments:
+#   ${@}: Dependencies and flags to add.
+################################################################################
+add() {
+    # Ensure command was run from project root
+    if [ $(in_root) -ne 1 ]; then
+        echo "Error: \"${PWD##*/}\" not a project root."
+        return
+    fi
+
+    # Add each dependency
+    for arg in "${@}"; do
+        case "$arg" in
+            "jfx" | "javafx") # Add JavaFX support
+                sed -i '/module/a requires javafx.controls;' src/$MODULE
+                ;;
+
+            *)
+                echo "Unsupported dependency \`$arg\`. Not yet implemented"
+                ;;
+        esac
+    done
+
+    echo -e "\t${YELLOW}ADDED${RESET} dependencies for project under \`$name/src/$MODULE\`"
 }
 
 ################################################################################
@@ -412,6 +508,11 @@ case $(echo $1 | tr '[:upper:]' '[:lower:]') in
     "doc" | "d") # Generate documentation for project
         shift
         doc ${@}
+        ;;
+
+    "add" | "d") # Adds dependencies to the project
+        shift
+        add ${@}
         ;;
 
     "--help" | "-h") # Display help menu
