feat: Help screen & documentation generation is done

diff --git a/jargo/jargo b/jargo/jargo
--- a/jargo/jargo
+++ b/jargo/jargo
@@ -29,6 +29,10 @@ package=""
 # Name of driver file
 driver=""
 
+# ANSI text colors
+RESET="\e[0m"
+YELLOW="\e[1;33m"
+
 #######################################
 
 # Initialize globals
@@ -46,7 +50,23 @@ fi
 # Displays usage message
 ################################################################################
 usage() {
-    echo "usage: jargo <COMMAND> [OPTIONS]"
+    echo "Simple Java Project Manager
+
+USAGE:
+    usage: jargo [OPTIONS] [COMMANDS]
+
+OPTIONS:
+    -h, --help          Display this menu
+        --list          List all commands
+
+COMMANDS:
+    new, n              Create a new Java project
+    build, b            Builds project, compiling classes if updates were made
+    run, r              Runs the driver for this project
+    clean, c            Cleans working directory of *.class files
+    doc, d              Generate documentation files
+
+See \`jargo help <COMMAND>\` for command-specific information"
 }
 
 ################################################################################
@@ -54,11 +74,24 @@ usage() {
 #
 # Arguments:
 #   $1: Error code to exit with
+#   ${@}: List of files to remove
 ################################################################################
 shutdown() {
     # Debug printing
-    #echo "Exiting with error code $1"
-    exit $1
+    #echo "Exiting with error code $exit_status"
+    
+    # Store exit code and shift to next arg
+    exit_status=$1
+    shift
+
+    # Remove all files in the remaining arguments
+    for arg in "${@}"; do
+        echo "Cleaning up: Removing $arg"
+        rm -rf $arg
+    done
+
+    # Exit with saved status
+    exit $exit_status
 }
 
 ################################################################################
@@ -82,7 +115,7 @@ new() {
 
     # Ensure a project name was passed in
     if [ -z "$name" ]; then
-        echo "usage: jargo new <NAME> [args]"
+        echo "usage: jargo new <NAME> [ARGS]"
         shutdown 3
     fi
 
@@ -141,23 +174,29 @@ driver:$driver" > $name/$CONFIG
  * @version $time
  */
 public class $driver {
+    /**
+     * Main
+     *
+     * @param args List of arguments supplied by executor.
+     */
     public static void main(String[] args) {
         System.out.println(\"Hello, world!\");
     }
 }" > $name/src/$package/$driver.java
 
     # Set up README.md
-    echo "# Title" > $name/README.md
+    echo "# $name " > $name/README.md
 
     # Initialize Git repository (if not disabled)
     if [ $git -eq 1 ]; then
         git init $name/ > /dev/null
         echo "*.class" > $name/.gitignore
         echo "bin/" >> $name/.gitignore
+        echo "docs/" >> $name/.gitignore
     fi
 
     # End
-    echo "Created new Java project: \"$name\""
+    echo -e "\t${YELLOW}CREATED${RESET} new Java project: \"$name\""
 }
 
 ################################################################################
@@ -181,13 +220,13 @@ build() {
         javac ${@} -d bin/ src/**/*.java
 
         # Display compilation message if no errors occurred
-        if [ $? -ne 0 ]; then
+        if [ $? -eq 0 ]; then
 
             # Display appropriate compilation message
             if [ ${#@} -gt 0 ]; then
-                echo -e "Compiled $name with args: ${@}\n"
+                echo -e "\t${YELLOW}COMPILED${RESET} $name with args: ${@}"
             else
-                echo -e "Compiled $name\n"
+                echo -e "\t${YELLOW}COMPILED${RESET} $name"
             fi
         fi
     else
@@ -222,9 +261,9 @@ run() {
     fi
 
     if [ ${#@} -gt 0 ]; then
-        echo -e "Executing $name with args: ${@}\n"
+        echo -e "\t${YELLOW}EXECUTING${RESET} $name with args: ${@}"
     else
-        echo -e "Executing $name\n"
+        echo -e "\t${YELLOW}EXECUTING${RESET} $name"
     fi
 
     # Execute driver with supplied args
@@ -247,9 +286,25 @@ clean() {
     # Recursively delete all *.class files in bin/
     find bin/ -name "*.class" -delete
 
-    echo "Cleaned project."
+    echo "\t${YELLOW}CLEANED${RESET} project binaries."
 }
 
+################################################################################
+# Generates documentation for the project
+################################################################################
+doc() {
+    # Ensure command was run from project root
+    if [ $(in_root) -ne 1 ]; then
+        echo "Error: \"${PWD##*/}\" not a project root."
+        return
+    fi
+
+    # Mute output when documenting, but display errors
+    javadoc -d docs src/**/*.java > /dev/null
+
+
+    echo -e "\t${YELLOW}GENERATED${RESET} docs for project under \`$name/docs/\`"
+}
 
 ################################################################################
 # Checks if the project needs to be recompiled.
@@ -308,25 +363,35 @@ if [ $# -lt 1 ]; then
 fi
 
 # Launch appropriate command
-case $1 in
-    "new") # Create new project
+case $(echo $1 | tr '[:upper:]' '[:lower:]') in
+    "new" | "n") # Create new project
         shift
         new ${@}
         ;;
 
-    "build") # Compile project
+    "build" | "b") # Compile project
         shift
         build ${@}
         ;;
 
-    "run") # Run project
+    "run" | "r") # Run project
         shift
         run ${@}
         ;;
 
-    "clean") # Clean project
+    "clean" | "c") # Clean project
         shift
         clean ${@}
+        ;;
+
+    "doc" | "d") # Generate documentation for project
+        shift
+        doc ${@}
+        ;;
+
+    "--help" | "-h") # Display help menu
+        shift
+        usage
         ;;
 
     *) # Unknown arg
@@ -335,4 +400,5 @@ case $1 in
         ;;
 esac
 
+# Program success
 exit 0
